### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by mtrojan-ub** [swordapp/swordappv2-php-library#16]
Is there any chance there will be a composer package for this project?

**Comment by stuartlewis** [comment]
Hi. This is no longer actively maintained, however if you wish to add the relevant code, we can include it in this repository via a pull request.

**Comment by mtrojan-ub** [comment]
Sounds good! I just opened up a pull request with a composer.json. Please also let me know if you would like to register it on packagist.org by yourself, or if you would like me to register it & add your account as maintainer later (if needed).

**Comment by stuartlewis** [comment]
Hi - thanks for the patch. This is now included, and registered with packagist... [https://packagist.org/packages/swordapp/swordappv2-php-library](https://packagist.org/packages/swordapp/swordappv2-php-library)

**Comment by mtrojan-ub** [comment]
Thanks!
