### ISSUE TITLE
The "--data-binary @-" argument is required to publish a Dataset while integrating with Dataverse

### ISSUE THREAD

**Issue by thiagolepidus** [swordapp/swordappv2-php-library#19]
Context: Integrating with a dataverse repository, and trying to publish a Dataset.

The HTTP status code 400 "Bad Request" is returned as the response for the requests.

This error occurs because the current version of Dataverse API requires a "--data-binary" argument into the curl command to publish a Dataverse Collection or a Dataset.

**Comment by stuartlewis** [comment]
Thanks - code merged.
